In [1]:
import pandas as pd
import numpy as np
train = pd.read_csv('features2.csv')
train.head(5)

AdoptionSpeed  MaturitySize  FurLength  Dewormed  Vaccinated  Sterilized  \
0              2             1          1         2           2           2   
1              0             2          2         3           3           3   
2              3             2          2         1           1           2   
3              2             2          1         1           1           2   
4              2             2          1         2           2           2   

   Health  Fee  Age  Breed1_0  ...  State_41330  State_41332  State_41335  \
0       1  100    3         0  ...            0            0            0   
1       1    0    1         0  ...            0            0            0   
2       1    0    1         0  ...            0            0            0   
3       1  150    4         0  ...            0            0            0   
4       1    0    1         0  ...            0            0            0   

   State_41336  State_41342  State_41345  State_41361  State_41367  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   State_41401  State_41415  
0            0            0  
1            1            0  
2            0            0  
3            1            0  
4            0            0  

[5 rows x 199 columns]

In [2]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder


train, y = train.iloc[:,1:],train.iloc[:,0]


X = train




In [3]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

/usr/lib/python3.7/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
/usr/lib/python3.7/site-packages/xgboost/core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [14]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [15]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt 
xgb.plot_importance(xg_reg,max_num_features = 20)
plt.rcParams['figure.figsize'] = [400, 350]
plt.show()




In [30]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

reg = lr.fit(X_train['Fee'].values.reshape(-1,1),y_train)

In [34]:
reg.coef_
reg.predict([[0],[50],[1000]])

array([2.51508309, 2.51289514, 2.47132418])

In [21]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

reg = lr.fit(X_train['Named'].values.reshape(-1,1),y_train)

In [22]:
reg.coef_

array([-0.08777394])

In [29]:
reg.predict([[0]])

array([2.5928])